package Acme::CPANLists::Import::PerlAdvent::2013_12_08;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2013/2013-12-08.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"App::PAUSE::CheckPerms"},{module=>"App::PAUSE::Comaint"},{module=>"PAUSE::Permissions"},{module=>"enum"}],summary=>"Modules mentioned in Perl Advent Calendar 2013 (day 08)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2013 (day 08)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2013/2013-12-08.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

