package Acme::CPANLists::Import::PerlAdvent::2013_12_07;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2013/2013-12-07.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"CGI"},{module=>"Catalyst"},{module=>"Corona"},{module=>"Dancer"},{module=>"FCGI"},{module=>"HTTP::Engine"},{module=>"HTTP::Server::Simple"},{module=>"Jifty"},{module=>"Mason"},{module=>"Mojolicious"},{module=>"OX"},{module=>"PSGI"},{module=>"Plack"},{module=>"Plack::Builder"},{module=>"Starlet"},{module=>"Starman"},{module=>"Tatsumaki"},{module=>"Twiggy"},{module=>"Web::Simple"}],summary=>"Modules mentioned in Perl Advent Calendar 2013 (day 07)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2013 (day 07)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2013/2013-12-07.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

