package Acme::CPANLists::Import::PerlAdvent::2013_12_09;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2013/2013-12-09.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Dist::Zilla::App::Command::msg_compile"},{module=>"Dist::Zilla::App::Command::msg_init"},{module=>"Dist::Zilla::App::Command::msg_merge"},{module=>"Dist::Zilla::LocaleTextDomain"},{module=>"ExtUtils::MakeMaker"},{module=>"Locale::Maketext"},{module=>"Locale::TextDomain"},{module=>"Module::Build"}],summary=>"Modules mentioned in Perl Advent Calendar 2013 (day 09)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2013 (day 09)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2013/2013-12-09.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

