package Acme::CPANLists::Import::PerlAdvent::2013_12_17;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2013/2013-12-17.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"DateTime::Duration"},{module=>"Time::Duration"},{module=>"Time::Duration::Object"},{module=>"Time::Duration::Parse"}],summary=>"Modules mentioned in Perl Advent Calendar 2013 (day 17)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2013 (day 17)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2013/2013-12-17.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

