package Acme::CPANLists::Import::PerlAdvent::2013_12_18;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2013/2013-12-18.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"File::Basename"},{module=>"File::Copy"},{module=>"File::Find"},{module=>"File::Path"},{module=>"File::Spec"},{module=>"File::Temp"},{module=>"File::stat"},{module=>"Path::Class"},{module=>"Path::Iterator::Rule"},{module=>"Path::Tiny"}],summary=>"Modules mentioned in Perl Advent Calendar 2013 (day 18)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2013 (day 18)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2013/2013-12-18.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

