package Acme::CPANLists::Import::PerlAdvent::2013_12_19;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2013/2013-12-19.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Moose"},{module=>"MooseX::StrictConstructor"},{module=>"fields"}],summary=>"Modules mentioned in Perl Advent Calendar 2013 (day 19)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2013 (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2013/2013-12-19.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

