package Acme::CPANLists::Import::PerlAdvent::2013_12_01;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2013/2013-12-01.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"RDF::Query"},{module=>"RDF::Query::Client"},{module=>"RDF::Trine"}],summary=>"Modules mentioned in Perl Advent Calendar 2013 (day 01)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2013 (day 01)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2013/2013-12-01.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

